**SONAR ROCK VS MINE PREDICTION USING SONAR DATA**


> WE HAVE TO PREDICT WHETHER THE OBJECT IS AN ROCK OR MINE

*IMPORTING THE REQUIRED LIBRARIES*

In [6]:
import pandas as pd
import numpy as np    # used to create numpy array
from sklearn.model_selection import train_test_split  # used to split the data into train and test
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

*DATA COLLECTION AND DATA PREPROCESSING*

In [10]:
# HERE WE ARE LOADING THE DATASET INTO THE DATAFRAME (df)
df = pd.read_csv("/content/Copy of sonar data.csv",header=None) # In our dataset there are no header name due to that we are keeping the header value as NONE
df.head()

       0       1       2       3       4   ...      56      57      58      59  60
0  0.0200  0.0371  0.0428  0.0207  0.0954  ...  0.0180  0.0084  0.0090  0.0032   R
1  0.0453  0.0523  0.0843  0.0689  0.1183  ...  0.0140  0.0049  0.0052  0.0044   R
2  0.0262  0.0582  0.1099  0.1083  0.0974  ...  0.0316  0.0164  0.0095  0.0078   R
3  0.0100  0.0171  0.0623  0.0205  0.0205  ...  0.0050  0.0044  0.0040  0.0117   R
4  0.0762  0.0666  0.0481  0.0394  0.0590  ...  0.0072  0.0048  0.0107  0.0094   R

[5 rows x 61 columns]

In [15]:
# TO FIND THE NUMBER OF ROWS AND COLUMNS OF THE DATASET
df.shape

(208, 61)

In [17]:
# IT GIVES THE STATISTICAL MEASURES OF THE DATA
df.describe()

               0           1           2   ...          57          58          59
count  208.000000  208.000000  208.000000  ...  208.000000  208.000000  208.000000
mean     0.029164    0.038437    0.043832  ...    0.007949    0.007941    0.006507
std      0.022991    0.032960    0.038428  ...    0.006470    0.006181    0.005031
min      0.001500    0.000600    0.001500  ...    0.000300    0.000100    0.000600
25%      0.013350    0.016450    0.018950  ...    0.003600    0.003675    0.003100
50%      0.022800    0.030800    0.034300  ...    0.005800    0.006400    0.005300
75%      0.035550    0.047950    0.057950  ...    0.010350    0.010325    0.008525
max      0.137100    0.233900    0.305900  ...    0.044000    0.036400    0.043900

[8 rows x 60 columns]

In [20]:
df[60].value_counts()

M    111
R     97
Name: 60, dtype: int64

M        MINE

R        ROCK

In [22]:
df.groupby(60).mean()

          0         1         2   ...        57        58        59
60                                ...
M   0.034989  0.045544  0.050720  ...  0.009060  0.008695  0.006930
R   0.022498  0.030303  0.035951  ...  0.006677  0.007078  0.006024

[2 rows x 60 columns]

In [23]:
# SEPARATING DATA AND LABELS
x = df.drop(columns=60,axis=1)
y = df[60]

In [26]:
x.head()

       0       1       2       3   ...      56      57      58      59
0  0.0200  0.0371  0.0428  0.0207  ...  0.0180  0.0084  0.0090  0.0032
1  0.0453  0.0523  0.0843  0.0689  ...  0.0140  0.0049  0.0052  0.0044
2  0.0262  0.0582  0.1099  0.1083  ...  0.0316  0.0164  0.0095  0.0078
3  0.0100  0.0171  0.0623  0.0205  ...  0.0050  0.0044  0.0040  0.0117
4  0.0762  0.0666  0.0481  0.0394  ...  0.0072  0.0048  0.0107  0.0094

[5 rows x 60 columns]

In [27]:
y.head()

0    R
1    R
2    R
3    R
4    R
Name: 60, dtype: object

TRAINING AND TEST DATA

In [28]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.1,stratify=y,random_state=1) # RANDOM STATE IS TO SPLIT THE DATA IN SAME MANNER

In [29]:
print(x.shape,x_train.shape,x_test.shape)

(208, 60) (187, 60) (21, 60)

In [33]:
print(x_train)
print(y_train)

         0       1       2       3   ...      56      57      58      59
115  0.0414  0.0436  0.0447  0.0844  ...  0.0141  0.0077  0.0246  0.0198
38   0.0123  0.0022  0.0196  0.0206  ...  0.0113  0.0058  0.0047  0.0071
56   0.0152  0.0102  0.0113  0.0263  ...  0.0037  0.0011  0.0034  0.0033
123  0.0270  0.0163  0.0341  0.0247  ...  0.0138  0.0094  0.0105  0.0093
18   0.0270  0.0092  0.0145  0.0278  ...  0.0120  0.0132  0.0070  0.0088
..      ...     ...     ...     ...  ...     ...     ...     ...     ...
140  0.0412  0.1135  0.0518  0.0232  ...  0.0095  0.0225  0.0098  0.0085
5    0.0286  0.0453  0.0277  0.0174  ...  0.0057  0.0027  0.0051  0.0062
154  0.0117  0.0069  0.0279  0.0583  ...  0.0020  0.0062  0.0026  0.0052
131  0.1150  0.1163  0.0866  0.0358  ...  0.0190  0.0141  0.0068  0.0086
203  0.0187  0.0346  0.0168  0.0177  ...  0.0065  0.0115  0.0193  0.0157

[187 rows x 60 columns]
115    M
38     R
56     R
123    M
18     R
      ..
140    M
5      R
154    M
131    M
203    M
Name: 60, Length: 187, dtype: object

TRAINING A MODEL


> LOGISTIC REGRESSION

In [31]:
model1 = LogisticRegression()

In [32]:
# TRAIN THE LOGISTIC REGRESSION MODEL  WITH THE TRAIN DATA
model1.fit(x_train,y_train)

LogisticRegression()

MODEL EVALUATION

In [34]:
# ACCURACY ON THE TRAINING DATA
x_train_prediction = model1.predict(x_train)
train_data_accuracy = accuracy_score(x_train_prediction,y_train)

In [37]:
print("ACCURACY SCORE ON TRAINING DATA : ",train_data_accuracy)

ACCURACY SCORE ON TRAINING DATA :  0.8342245989304813

In [38]:
# ACCURACY ON THE TEST DATA
x_test_prediction = model1.predict(x_test)
test_data_accuracy = accuracy_score(x_test_prediction,y_test)

In [40]:
print("ACCURACY SCORE ON TEST DATA : ",test_data_accuracy)

ACCURACY SCORE ON TEST DATA :  0.7619047619047619

MAKING AN PREDICTION

In [42]:
input_data = (0.0298,0.0615,0.0650,0.0921,0.1615,0.2294,0.2176,0.2033,0.1459,0.0852,0.2476,0.3645,0.2777,0.2826,0.3237,0.4335,0.5638,0.4555,0.4348,0.6433,0.3932,0.1989,0.3540,0.9165,0.9371,0.4620,0.2771,0.6613,0.8028,0.4200,0.5192,0.6962,0.5792,0.8889,0.7863,0.7133,0.7615,0.4401,0.3009,0.3163,0.2809,0.2898,0.0526,0.1867,0.1553,0.1633,0.1252,0.0748,0.0452,0.0064,0.0154,0.0031,0.0153,0.0071,0.0212,0.0076,0.0152,0.0049,0.0200,0.0073)
# converting the input_data to an numpy_array
input_data_as_numpy_array = np.asarray(input_data)
# RESHAPE THE NUMPY ARRAY BECAUSE WE ARE PREDICTING FOR ONE INSTANCE
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

prediction = model1.predict(input_data_reshaped)
print(prediction)

if(prediction[0]=='R'):
  print("THE OBJECT IS A ROCK")
else:
  print("THE OBJECT IS MINE")

['R']
THE OBJECT IS A ROCK